# Generated by Django 5.0.6 on 2026-03-20 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=20)),
                ('school_year', models.CharField(max_length=20)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ComputerUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_tag', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LabRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Operational', 'Operational'), ('Maintenance', 'Maintenance')], default='Operational', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('model_number', models.CharField(blank=True, max_length=100)),
                ('cpu', models.CharField(max_length=50)),
                ('ram', models.CharField(max_length=50)),
                ('storage', models.CharField(max_length=50)),
                ('gpu', models.CharField(max_length=50)),
                ('network_adapter', models.CharField(blank=True, max_length=100)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('warranty_status', models.CharField(blank=True, max_length=50)),
                ('condition', models.CharField(choices=[('Fair', 'Fair'), ('Good', 'Good'), ('Poor', 'Poor')], default='Good', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='system.computerunit')),
            ],
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_checked', models.DateField()),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.assessmentperiod')),
                ('unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='system.computerunit')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.technician')),
            ],
        ),
        migrations.CreateModel(
            name='ConditionRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hardware_condition', models.CharField(max_length=50)),
                ('software_condition', models.CharField(max_length=50)),
                ('remarks', models.TextField()),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.inspection')),
            ],
        ),
        migrations.AddField(
            model_name='computerunit',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.labroom'),
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os', models.CharField(max_length=50)),
                ('installed_apps', models.TextField()),
                ('unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='system.computerunit')),
            ],
        ),
    ]
