# Generated by Django 5.0.6 on 2026-03-21 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardware',
            name='condition',
            field=models.CharField(choices=[('Poor', 'Poor'), ('Fair', 'Fair'), ('Good', 'Good')], default='Good', max_length=20),
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('serial_number', models.CharField(max_length=100)),
                ('condition', models.CharField(max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.computerunit')),
            ],
        ),
    ]
