# Generated by Django 5.0.6 on 2026-03-21 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_alter_hardware_condition_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardware',
            name='condition',
            field=models.CharField(choices=[('Fair', 'Fair'), ('Poor', 'Poor'), ('Good', 'Good')], default='Good', max_length=20),
        ),
    ]
