# Generated by Django 5.0.6 on 2026-03-21 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_alter_hardware_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditionrating',
            name='inspection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='system.inspection'),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='condition',
            field=models.CharField(choices=[('Poor', 'Poor'), ('Good', 'Good'), ('Fair', 'Fair')], default='Good', max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='unit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inspection', to='system.computerunit'),
        ),
    ]
