# Generated by Django 5.0.6 on 2026-03-21 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_alter_conditionrating_inspection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardware',
            name='condition',
            field=models.CharField(choices=[('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor')], default='Good', max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection', to='system.computerunit'),
        ),
    ]
