# Generated by Django 5.0.6 on 2026-03-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_alter_hardware_condition_alter_inspection_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardware',
            name='condition',
            field=models.CharField(choices=[('Fair', 'Fair'), ('Poor', 'Poor'), ('Good', 'Good')], default='Good', max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='date_checked',
            field=models.DateField(auto_now_add=True),
        ),
    ]
