# Generated by Django 5.0.6 on 2026-03-21 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_alter_hardware_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardware',
            name='condition',
            field=models.CharField(choices=[('Poor', 'Poor'), ('Fair', 'Fair'), ('Good', 'Good')], default='Good', max_length=20),
        ),
    ]
