# Generated by Django 5.0.6 on 2026-03-21 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_technician_specialty_technician_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='lab',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.labroom'),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.computerunit'),
        ),
        migrations.AlterField(
            model_name='software',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.computerunit'),
        ),
    ]
