# Generated by Django 5.0.6 on 2026-03-22 04:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_equipment_lab_alter_hardware_unit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='room',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='system.labroom'),
        ),
        migrations.AddField(
            model_name='technician',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='computerunit',
            name='status',
            field=models.CharField(choices=[('Working', 'Working'), ('Defective', 'Defective'), ('Maintenance', 'Maintenance')], max_length=50),
        ),
    ]
