# Generated by Django 5.0.6 on 2026-03-22 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_inspection_room_technician_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Technician', 'Technician')], default='Technician', max_length=20),
        ),
    ]
