# Generated by Django 5.0.6 on 2026-03-23 01:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0012_remove_inspection_room_inspection_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='system.computerunit'),
        ),
    ]
