# Generated by Django 5.0.6 on 2026-03-24 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0013_inspection_created_at_alter_inspection_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardware',
            name='cpu',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='gpu',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='ram',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='storage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
