# Generated by Django 5.0.6 on 2026-03-24 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0014_alter_hardware_cpu_alter_hardware_gpu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditionrating',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.computerunit'),
        ),
    ]
